# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: base_data.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'base_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62\x61se_data.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x17\n\x07ListInt\x12\x0c\n\x04list\x18\x01 \x03(\r\"\x18\n\x08ListLong\x12\x0c\n\x04list\x18\x01 \x03(\x04\"\x19\n\tListFloat\x12\x0c\n\x04list\x18\x01 \x03(\x02\"\x1a\n\nListString\x12\x0c\n\x04list\x18\x01 \x03(\t\"\x18\n\x08ListBool\x12\x0c\n\x04list\x18\x01 \x03(\x08\"8\n\x0cListDatetime\x12(\n\x04list\x18\x01 \x03(\x0b\x32\x1a.google.protobuf.Timestamp\"\x9c\x03\n\x08\x42\x61seData\x12\x12\n\x08int_data\x18\x01 \x01(\rH\x00\x12\x13\n\tlong_data\x18\x02 \x01(\x04H\x00\x12\x14\n\nfloat_data\x18\x03 \x01(\x02H\x00\x12\x15\n\x0bstring_data\x18\x04 \x01(\tH\x00\x12\x13\n\tbool_data\x18\x05 \x01(\x08H\x00\x12\x33\n\rdatetime_data\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x12!\n\rlist_int_data\x18\x07 \x01(\x0b\x32\x08.ListIntH\x00\x12#\n\x0elist_long_data\x18\x08 \x01(\x0b\x32\t.ListLongH\x00\x12%\n\x0flist_float_data\x18\t \x01(\x0b\x32\n.ListFloatH\x00\x12\'\n\x10list_string_data\x18\n \x01(\x0b\x32\x0b.ListStringH\x00\x12#\n\x0elist_bool_data\x18\x0b \x01(\x0b\x32\t.ListBoolH\x00\x12+\n\x12list_datetime_data\x18\x0c \x01(\x0b\x32\r.ListDatetimeH\x00\x42\x06\n\x04\x64\x61tab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'base_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTINT']._serialized_start=52
  _globals['_LISTINT']._serialized_end=75
  _globals['_LISTLONG']._serialized_start=77
  _globals['_LISTLONG']._serialized_end=101
  _globals['_LISTFLOAT']._serialized_start=103
  _globals['_LISTFLOAT']._serialized_end=128
  _globals['_LISTSTRING']._serialized_start=130
  _globals['_LISTSTRING']._serialized_end=156
  _globals['_LISTBOOL']._serialized_start=158
  _globals['_LISTBOOL']._serialized_end=182
  _globals['_LISTDATETIME']._serialized_start=184
  _globals['_LISTDATETIME']._serialized_end=240
  _globals['_BASEDATA']._serialized_start=243
  _globals['_BASEDATA']._serialized_end=655
# @@protoc_insertion_point(module_scope)
