# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: session.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import base_data_pb2 as base__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsession.proto\x1a\x0f\x62\x61se_data.proto\"x\n\tTagUpdate\x12\"\n\x04tags\x18\x01 \x03(\x0b\x32\x14.TagUpdate.TagsEntry\x12\x0f\n\x07meta_ts\x18\x02 \x01(\x06\x1a\x36\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.BaseData:\x02\x38\x01\"o\n\nMethodCall\x12\'\n\x06params\x18\x01 \x03(\x0b\x32\x17.MethodCall.ParamsEntry\x1a\x38\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.BaseData:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAGUPDATE_TAGSENTRY']._loaded_options = None
  _globals['_TAGUPDATE_TAGSENTRY']._serialized_options = b'8\001'
  _globals['_METHODCALL_PARAMSENTRY']._loaded_options = None
  _globals['_METHODCALL_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_TAGUPDATE']._serialized_start=34
  _globals['_TAGUPDATE']._serialized_end=154
  _globals['_TAGUPDATE_TAGSENTRY']._serialized_start=100
  _globals['_TAGUPDATE_TAGSENTRY']._serialized_end=154
  _globals['_METHODCALL']._serialized_start=156
  _globals['_METHODCALL']._serialized_end=267
  _globals['_METHODCALL_PARAMSENTRY']._serialized_start=211
  _globals['_METHODCALL_PARAMSENTRY']._serialized_end=267
# @@protoc_insertion_point(module_scope)
